apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1 
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongodb/mongodb-community-server:latest
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitstamp-feeder
spec:
  selector:
    matchLabels:
      app: bitstamp-feeder
  replicas: 1
  template:
    metadata:
      labels:
        app: bitstamp-feeder
    spec:
      initContainers:
      - name: wait-for-mongodb
        image: busybox
        command: ['sh', '-c', 'until nc -z -v -w30 mongodb 27017; do echo "waiting for mongodb"; sleep 5; done']
      containers:
      - name: bitstamp-feeder
        image: bzero/bitstamp-feeder:latest 
