apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitstamp-feeder
spec:
  selector:
    matchLabels:
      app: bitstamp-feeder
  replicas: 1
  template:
    metadata:
      labels:
        app: bitstamp-feeder
    spec:
      initContainers:
      - name: wait-for-mongodb
        image: busybox
        command: ['sh', '-c', 'until nc -z -v -w30 mongodb 27017; do echo "waiting for mongodb"; sleep 5; done']
      containers:
      - name: bitstamp-feeder
        image: bzero/bitstamp-feeder:latest 
